const {chromium}=require('playwright');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome',args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 let historyRequests=0;
 const state={id:'fixture',status:'running',total:2,config:{rounds:1,games_per_round:2,left:{name:'Blue'},right:{name:'Orange'}},matches:[{round:1,game:1,status:'completed',left_team:'Blue',right_team:'Orange',left_score:2,right_score:1}],progress:{round:1,game:2,cycle:3500,expected_cycles:6000,percent:58.3,left_score:3,right_score:2,frame:{cycle:3500,mode:'3',names:['Blue','Orange'],score:[3,2],ball:[1,2],players:[['l',1,-45,0,0,true],['r',9,20,10,90,false]]}}};
 const replay={version:1,step_ms:100,final_score:[2,1],frames:[{...state.progress.frame,cycle:1,score:[0,0]},{...state.progress.frame,cycle:6000,score:[2,1]}]};
 await page.route('http://arena.test/**',async route=>{const u=new URL(route.request().url());let body;
 if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync('static/index.html','utf8')});
 if(u.pathname.endsWith('/live'))return route.fulfill({contentType:'text/event-stream',body:'retry: 10000\n\ndata: '+JSON.stringify({frames:[{round:1,game:2,frame:{...state.progress.frame,cycle:3501},captured_at:Date.now()/1000}]})+'\n\n'});
 if(u.pathname==='/api/teams')body=[];
 else if(u.pathname==='/api/tests'){historyRequests++;body=[{id:'fixture',started_at:'2026-10-07'}];}
 else if(u.pathname.includes('/replay/'))body=replay;
 else body=state;
 await route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
 });
 await page.goto('http://arena.test/');
 assert.equal(historyRequests,0,'Opening the site must not request previous tests');
 assert.equal(await page.locator('#monitorScore').textContent(),'— : —');
 await page.locator('#recent').click();
 await page.waitForFunction(()=>document.getElementById('monitorScore').textContent==='3 : 2');
 await page.waitForFunction(()=>document.getElementById('monitorBadge').textContent==='پخش مستقیم');
 assert.equal(await page.locator('#monitorMatch option').count(),2);
 assert.equal(JSON.parse(await page.locator('#json').textContent()).progress.frame,undefined);
 await page.locator('.personalization summary').click();await page.locator('#themeLight').click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 assert.equal(await page.locator('body').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(244, 247, 251)');
 await page.reload();await page.locator('#recent').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await page.waitForFunction(()=>document.getElementById('monitorScore').textContent==='3 : 2');
 await page.locator('.personalization summary').click();await page.locator('#themeDark').click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.selectOption('#monitorMatch','1/1');await page.waitForFunction(()=>!document.getElementById('monitorPlay').disabled);
 assert.equal(await page.locator('#monitorScore').textContent(),'0 : 0');
 await page.locator('#monitorSeek').fill('1');await page.locator('#monitorSeek').dispatchEvent('input');
 assert.equal(await page.locator('#monitorScore').textContent(),'2 : 1');
 await page.selectOption('#monitorMatch','1/2');assert.equal(await page.locator('#monitorScore').textContent(),'3 : 2');
 await page.locator('#matchMonitor').screenshot({path:'/tmp/arena-monitor-desktop.png'});
 await page.setViewportSize({width:390,height:844});await page.locator('#matchMonitor').screenshot({path:'/tmp/arena-monitor-mobile.png'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.selectOption('#monitorSource','file');
 await page.locator('#monitorFile').setInputFiles({name:'local-match.rcg',mimeType:'text/plain',buffer:Buffer.from('ULG6\n(team 0 LocalBlue LocalOrange 1 2)\n(show 1 ((b) 0 0 0 0) ((l 1) 0 9 -40 0 0 0 90))\n(show 6000 ((b) 10 0 0 0))\n(playmode 6000 time_over)\n')});
 await page.waitForFunction(()=>document.getElementById('monitorLeft').textContent==='LocalBlue');
 assert.equal(await page.locator('#monitorScore').textContent(),'1 : 2');
 await page.locator('#monitorSeek').fill('1');await page.locator('#monitorSeek').dispatchEvent('input');
 assert.match(await page.locator('#monitorCycle').textContent(),/6000/);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.selectOption('#monitorSource','server');assert.equal(await page.locator('#monitorFilePanel').isVisible(),false);
 assert.deepEqual(errors,[]);console.log('PASS: live positions, game selection, replay seeking, score, desktop/mobile layout');await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});
